// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class RequestVRF extends ethereum.Event {
  get params(): RequestVRF__Params {
    return new RequestVRF__Params(this);
  }
}

export class RequestVRF__Params {
  _event: RequestVRF;

  constructor(event: RequestVRF) {
    this._event = event;
  }

  get roller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get requestId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get topic(): string {
    return this._event.parameters[2].value.toString();
  }
}

export class ResponseVRF extends ethereum.Event {
  get params(): ResponseVRF__Params {
    return new ResponseVRF__Params(this);
  }
}

export class ResponseVRF__Params {
  _event: ResponseVRF;

  constructor(event: ResponseVRF) {
    this._event = event;
  }

  get requestId(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get randomness(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get topic(): string {
    return this._event.parameters[2].value.toString();
  }

  get success(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get reason(): string {
    return this._event.parameters[4].value.toString();
  }
}

export class Updated extends ethereum.Event {
  get params(): Updated__Params {
    return new Updated__Params(this);
  }
}

export class Updated__Params {
  _event: Updated;

  constructor(event: Updated) {
    this._event = event;
  }

  get value(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get actionType(): string {
    return this._event.parameters[1].value.toString();
  }
}

export class OmnuumVRFManager extends ethereum.SmartContract {
  static bind(address: Address): OmnuumVRFManager {
    return new OmnuumVRFManager("OmnuumVRFManager", address);
  }

  aToId(param0: Address): Bytes {
    let result = super.call("aToId", "aToId(address):(bytes32)", [
      ethereum.Value.fromAddress(param0)
    ]);

    return result[0].toBytes();
  }

  try_aToId(param0: Address): ethereum.CallResult<Bytes> {
    let result = super.tryCall("aToId", "aToId(address):(bytes32)", [
      ethereum.Value.fromAddress(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  idToA(param0: Bytes): Address {
    let result = super.call("idToA", "idToA(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);

    return result[0].toAddress();
  }

  try_idToA(param0: Bytes): ethereum.CallResult<Address> {
    let result = super.tryCall("idToA", "idToA(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  idToTopic(param0: Bytes): string {
    let result = super.call("idToTopic", "idToTopic(bytes32):(string)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);

    return result[0].toString();
  }

  try_idToTopic(param0: Bytes): ethereum.CallResult<string> {
    let result = super.tryCall("idToTopic", "idToTopic(bytes32):(string)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  safetyRatio(): i32 {
    let result = super.call("safetyRatio", "safetyRatio():(uint16)", []);

    return result[0].toI32();
  }

  try_safetyRatio(): ethereum.CallResult<i32> {
    let result = super.tryCall("safetyRatio", "safetyRatio():(uint16)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _LINK(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _vrf_coord(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _key_hash(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }

  get _fee(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }

  get _omnuumCA(): Address {
    return this._call.inputValues[4].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class RawFulfillRandomnessCall extends ethereum.Call {
  get inputs(): RawFulfillRandomnessCall__Inputs {
    return new RawFulfillRandomnessCall__Inputs(this);
  }

  get outputs(): RawFulfillRandomnessCall__Outputs {
    return new RawFulfillRandomnessCall__Outputs(this);
  }
}

export class RawFulfillRandomnessCall__Inputs {
  _call: RawFulfillRandomnessCall;

  constructor(call: RawFulfillRandomnessCall) {
    this._call = call;
  }

  get requestId(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get randomness(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class RawFulfillRandomnessCall__Outputs {
  _call: RawFulfillRandomnessCall;

  constructor(call: RawFulfillRandomnessCall) {
    this._call = call;
  }
}

export class RequestVRFCall extends ethereum.Call {
  get inputs(): RequestVRFCall__Inputs {
    return new RequestVRFCall__Inputs(this);
  }

  get outputs(): RequestVRFCall__Outputs {
    return new RequestVRFCall__Outputs(this);
  }
}

export class RequestVRFCall__Inputs {
  _call: RequestVRFCall;

  constructor(call: RequestVRFCall) {
    this._call = call;
  }

  get _topic(): string {
    return this._call.inputValues[0].value.toString();
  }
}

export class RequestVRFCall__Outputs {
  _call: RequestVRFCall;

  constructor(call: RequestVRFCall) {
    this._call = call;
  }
}

export class RequestVRFOnceCall extends ethereum.Call {
  get inputs(): RequestVRFOnceCall__Inputs {
    return new RequestVRFOnceCall__Inputs(this);
  }

  get outputs(): RequestVRFOnceCall__Outputs {
    return new RequestVRFOnceCall__Outputs(this);
  }
}

export class RequestVRFOnceCall__Inputs {
  _call: RequestVRFOnceCall;

  constructor(call: RequestVRFOnceCall) {
    this._call = call;
  }

  get _targetAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _topic(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class RequestVRFOnceCall__Outputs {
  _call: RequestVRFOnceCall;

  constructor(call: RequestVRFOnceCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class UpdateFeeCall extends ethereum.Call {
  get inputs(): UpdateFeeCall__Inputs {
    return new UpdateFeeCall__Inputs(this);
  }

  get outputs(): UpdateFeeCall__Outputs {
    return new UpdateFeeCall__Outputs(this);
  }
}

export class UpdateFeeCall__Inputs {
  _call: UpdateFeeCall;

  constructor(call: UpdateFeeCall) {
    this._call = call;
  }

  get _fee(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class UpdateFeeCall__Outputs {
  _call: UpdateFeeCall;

  constructor(call: UpdateFeeCall) {
    this._call = call;
  }
}

export class UpdateSafetyRatioCall extends ethereum.Call {
  get inputs(): UpdateSafetyRatioCall__Inputs {
    return new UpdateSafetyRatioCall__Inputs(this);
  }

  get outputs(): UpdateSafetyRatioCall__Outputs {
    return new UpdateSafetyRatioCall__Outputs(this);
  }
}

export class UpdateSafetyRatioCall__Inputs {
  _call: UpdateSafetyRatioCall;

  constructor(call: UpdateSafetyRatioCall) {
    this._call = call;
  }

  get _safetyRatio(): i32 {
    return this._call.inputValues[0].value.toI32();
  }
}

export class UpdateSafetyRatioCall__Outputs {
  _call: UpdateSafetyRatioCall;

  constructor(call: UpdateSafetyRatioCall) {
    this._call = call;
  }
}
